from app import db
from api.hero.models import Hero

def add_all_ow_heroes():
    ana = Hero(name='Ana')
    db.session.add(ana)
    db.session.commit()
    ashe = Hero(name='Ashe')
    db.session.add(ashe)
    db.session.commit()
    bap = Hero(name='Baptiste')
    db.session.add(bap)
    db.session.commit()
    bastion = Hero(name='Bastion')
    db.session.add(bastion)
    db.session.commit()
    brig = Hero(name='Brigitte')
    db.session.add(brig)
    db.session.commit
    dva = Hero(name='D.Va')
    db.session.add(dva)
    db.session.commit()
    doom = Hero(name='Doomfist')
    db.session.add(doom)
    db.session.commit()
    echo = Hero(name='Echo')
    db.session.add(echo)
    db.session.commit()
    genji = Hero(name='Genji')
    db.session.add(genji)
    db.session.commit()
    hanzo = Hero(name='Hanzo')
    db.session.add(hanzo)
    db.session.commit()
    junk = Hero(name='Junkrat')
    db.session.add(junk)
    db.session.commit()
    lucio = Hero(name='Lucio')
    db.session.add(lucio)
    db.session.commit()
    mcree = Hero(name='Cassidy')
    db.session.add(mcree)
    db.session.commit()
    mei = Hero(name='Mei')
    db.session.add(mei)
    db.session.commit()
    mercy = Hero(name='Mercy')
    db.session.add(mercy)
    db.session.commit()
    moira = Hero(name='Moira')
    db.session.add(moira)
    db.session.commit()
    orisa = Hero(name='Orisa')
    db.session.add(orisa)
    db.session.commit()
    pharah = Hero(name='Pharah')
    db.session.add(pharah)
    db.session.commit()
    reaper = Hero(name='Reaper')
    db.session.add(reaper)
    db.session.commit()
    rein = Hero(name='Reinhardt')
    db.session.add(rein)
    db.session.commit()
    hog = Hero(name='Roadhog')
    db.session.add(hog)
    db.session.commit()
    sigma = Hero(name='Sigma')
    db.session.add(sigma)
    db.session.commit()
    soldier = Hero(name='Soldier:76')
    sombra = Hero(name='Sombra')
    db.session.add(sombra)
    db.session.commit()
    sym = Hero(name='Symmetra')
    db.session.add(sym)
    db.session.commit()
    torb = Hero(name='Torbjorn')
    db.session.add(torb)
    db.session.commit()
    tracer = Hero(name='Tracer')
    db.session.add(tracer)
    db.session.commit()
    widow = Hero(name='Widowmaker')
    db.session.add(widow)
    db.session.commit()
    winston = Hero(name='Winston')
    db.session.add(winston)
    db.session.commit()
    ball = Hero(name='Wrecking Ball')
    db.session.add(ball)
    db.session.commit()
    zarya = Hero(name='Zarya')
    db.session.add(zarya)
    db.session.commit()
    zen = Hero(name='Zenyatta')
    db.session.add(zen)
    db.session.commit()