from app import db
from api.hero.models import Hero

def add_all_ow_heroes():
    ana = Hero(name='Ana')
    db.session.add(ana)
    db.session.commit()
    ashe = Hero(name='Ashe')
    db.session.add(ashe)
    db.session.commit()
    bap = Hero(name='Baptiste')
    db.session.add(bap)
    db.session.commit()
    bastion = Hero(name='Bastion')
    db.session.add(bastion)
    db.session.commit()
    brig = Hero(name='Brigitte')
    db.session.add(brig)
    db.session.commit
    dva = Hero(name='D.Va')
    db.session.add(dva)
    db.session.commit()
    doom = Hero(name='Doomfist')
    db.session.add(doom)
    db.session.commit()
    echo = Hero(name='Echo')
    db.session.add(echo)
    db.session.commit()
    genji = Hero(name='Genji')
    db.session.add(genji)
    db.session.commit()