from app import db
from app import Hero, Map

def add_all_ow_heroes():
    winston = Hero(name="Winston")
    db.session.add(winston)
    reinhardt = Hero(name="Reinhardt")
    db.session.add(reinhardt)
    zarya = Hero(name="Zarya")
    db.session.add(zarya)
    dva = Hero(name="D.Va")
    db.session.add(dva)
    sigma = Hero(name="Sigma")
    db.session.add(sigma)
    roadhog = Hero(name="Roadhog")
    db.session.add(roadhog)
    wrecking_ball = Hero(name="Wrecking Ball")
    db.session.add(wrecking_ball)
    orisa = Hero(name="Orisa")
    db.session.add(orisa)
    db.session.commit()

def add_all_ow_maps():
    hollywood = Map(name="HOLLYWOOD")
    db.session.add(hollywood)
    havana = Map(name="HAVANA")
    db.session.add(havana)
    nepal = Map(name="NEPAL")
    db.session.add(nepal)
    numbani = Map(name="NUMBANI")
    db.session.add(numbani)
    ilios = Map(name="ILIOS")
    db.session.add(ilios)
    blizzard_world = Map(name="BLIZZARD WORLD")
    db.session.add(blizzard_world)
    volskaya_industries = Map(name="VOLSKAYA INDUSTRIES")
    db.session.add(volskaya_industries)
    kings_row = Map(name="KING'S ROW")
    db.session.add(kings_row)
    db.session.commit()