"""made ranked flag in matches table to be non-nullable

Revision ID: 08fc0d97cb5d
Revises: ab1fcdf1e8d0
Create Date: 2022-05-06 16:21:00.222914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08fc0d97cb5d'
down_revision = 'ab1fcdf1e8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ow_match', 'ranked_flag',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('ow_match_round', 'phase',
               existing_type=mysql.ENUM('ATTACK', 'DEFEND', 'CONTROL'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ow_match_round', 'phase',
               existing_type=mysql.ENUM('ATTACK', 'DEFEND', 'CONTROL'),
               nullable=False)
    op.alter_column('ow_match', 'ranked_flag',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
