"""added new association table for heroes and matches

Revision ID: 256c1a7190fb
Revises: f0acd7de2407
Create Date: 2022-03-24 22:39:49.314686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256c1a7190fb'
down_revision = 'f0acd7de2407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ow_match', sa.Column('hero_role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ow_match', 'ow_hero_role', ['hero_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ow_match', type_='foreignkey')
    op.drop_column('ow_match', 'hero_role_id')
    # ### end Alembic commands ###
