"""updated association 

Revision ID: 4ebf9fb08988
Revises: 256c1a7190fb
Create Date: 2022-03-24 23:16:35.820775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ebf9fb08988'
down_revision = '256c1a7190fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ow_match_hero', sa.Column('match_id', sa.Integer(), nullable=False))
    op.drop_constraint('ow_match_hero_ibfk_2', 'ow_match_hero', type_='foreignkey')
    op.create_foreign_key(None, 'ow_match_hero', 'ow_match', ['match_id'], ['id'])
    op.drop_column('ow_match_hero', 'right_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ow_match_hero', sa.Column('right_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ow_match_hero', type_='foreignkey')
    op.create_foreign_key('ow_match_hero_ibfk_2', 'ow_match_hero', 'ow_match', ['right_id'], ['id'])
    op.drop_column('ow_match_hero', 'match_id')
    # ### end Alembic commands ###
