"""added accepted_flag to MatchUser

Revision ID: 56bf4896d66d
Revises: 5d59f8420bea
Create Date: 2022-07-27 22:16:34.098922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56bf4896d66d'
down_revision = '5d59f8420bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ow_match_user', sa.Column('accepted_flag', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ow_match_user', 'accepted_flag')
    # ### end Alembic commands ###
