"""updated match user hero pks

Revision ID: 6705403d9eef
Revises: 1760a28a7cc2
Create Date: 2022-09-02 04:14:31.057696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6705403d9eef'
down_revision = '1760a28a7cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ow_match_user_hero', 'match_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('ow_match_user_hero', 'hero_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ow_match_user_hero', 'hero_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('ow_match_user_hero', 'match_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
