"""removed TaggedUser relationship from Match class

Revision ID: 8b62a19abc3e
Revises: 7a272d092f2a
Create Date: 2022-09-05 14:41:04.629928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b62a19abc3e'
down_revision = '7a272d092f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ow_match_tagged_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ow_match_tagged_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('match_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['ow_match.id'], name='ow_match_tagged_user_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='ow_match_tagged_user_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
