"""added score to match round and added max_score to map mode

Revision ID: 9b05206b1f6f
Revises: 08fc0d97cb5d
Create Date: 2022-05-16 23:18:56.069296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b05206b1f6f'
down_revision = '08fc0d97cb5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend')
    op.add_column('ow_map_mode', sa.Column('max_score', sa.Integer(), nullable=True))
    op.add_column('ow_match_round', sa.Column('score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ow_match_round', 'score')
    op.drop_column('ow_map_mode', 'max_score')
    op.create_table('friend',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('friend_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name='friend_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='friend_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'friend_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
