"""removed hero_role_id from Match class

Revision ID: 9ec6bb5def62
Revises: 4ebf9fb08988
Create Date: 2022-03-27 14:35:03.341189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ec6bb5def62'
down_revision = '4ebf9fb08988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ow_match_ibfk_3', 'ow_match', type_='foreignkey')
    op.drop_column('ow_match', 'hero_role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ow_match', sa.Column('hero_role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('ow_match_ibfk_3', 'ow_match', 'ow_hero_role', ['hero_role_id'], ['id'])
    # ### end Alembic commands ###
