"""changed user_id to created_by_user_id

Revision ID: a6f3d8ce8384
Revises: d975d87331c2
Create Date: 2022-07-31 22:34:25.421626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6f3d8ce8384'
down_revision = 'd975d87331c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ow_match', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('ow_match_ibfk_2', 'ow_match', type_='foreignkey')
    op.create_foreign_key(None, 'ow_match', 'user', ['created_by_user_id'], ['id'])
    op.drop_column('ow_match', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ow_match', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ow_match', type_='foreignkey')
    op.create_foreign_key('ow_match_ibfk_2', 'ow_match', 'user', ['user_id'], ['id'])
    op.drop_column('ow_match', 'created_by_user_id')
    # ### end Alembic commands ###
