"""update to fk

Revision ID: d233347ec020
Revises: 56bf4896d66d
Create Date: 2022-07-28 16:51:00.198306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd233347ec020'
down_revision = '56bf4896d66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ow_match_user_hero_ibfk_2', 'ow_match_user_hero', type_='foreignkey')
    op.create_foreign_key(None, 'ow_match_user_hero', 'ow_match_user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ow_match_user_hero', type_='foreignkey')
    op.create_foreign_key('ow_match_user_hero_ibfk_2', 'ow_match_user_hero', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
