"""Adding Match ID to Match Round table

Revision ID: f0acd7de2407
Revises: 0c299896e7c4
Create Date: 2022-03-13 22:43:14.203359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0acd7de2407'
down_revision = '0c299896e7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ow_match_round', sa.Column('match_id', sa.Integer(), nullable=True))
    op.create_foreign_key("ow_match_round_ow_match_fk", 'ow_match_round', 'ow_match', ['match_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ow_match_round_ow_match_fk", 'ow_match_round', type_='foreignkey')
    op.drop_column('ow_match_round', 'match_id')
    # ### end Alembic commands ###
