"""Rebuilding

Revision ID: 0c299896e7c4
Revises: 823b73b71138
Create Date: 2022-03-13 21:58:26.218103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c299896e7c4'
down_revision = '823b73b71138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_email', table_name='_user_gho')
    op.drop_table('_user_gho')
    op.drop_index('hint_uidx', table_name='_user_ghc')
    op.drop_table('_user_ghc')
    op.add_column('ow_map', sa.Column('map_mode_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ow_map', 'ow_map_mode', ['map_mode_id'], ['id'])
    op.create_foreign_key(None, 'ow_match', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ow_match', type_='foreignkey')
    op.drop_constraint(None, 'ow_map', type_='foreignkey')
    op.drop_column('ow_map', 'map_mode_id')
    op.create_table('_user_ghc',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('hint', mysql.VARCHAR(charset='ascii', length=64), nullable=False),
    sa.Column('value', mysql.VARCHAR(charset='ascii', length=4096), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('hint_uidx', '_user_ghc', ['hint'], unique=False)
    op.create_table('_user_gho',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('user_email', '_user_gho', ['email'], unique=False)
    # ### end Alembic commands ###
