"""updated date_played column name to date_match_played and added new_date_created column

Revision ID: 5d59f8420bea
Revises: e271738b13f2
Create Date: 2022-05-23 15:20:50.159384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d59f8420bea'
down_revision = 'e271738b13f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ow_match', sa.Column('date_match_played', sa.DateTime(), nullable=True))
    op.add_column('ow_match', sa.Column('date_match_created', sa.DateTime(), nullable=True))
    op.drop_column('ow_match', 'date_played')
    op.drop_column('ow_match', 'result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ow_match', sa.Column('result', mysql.ENUM('VICTORY', 'DEFEAT', 'DRAW'), nullable=True))
    op.add_column('ow_match', sa.Column('date_played', mysql.DATETIME(), nullable=True))
    op.drop_column('ow_match', 'date_match_created')
    op.drop_column('ow_match', 'date_match_played')
    # ### end Alembic commands ###
