"""added hero role id to match user class

Revision ID: 7a272d092f2a
Revises: bee8e7cc7f20
Create Date: 2022-09-05 14:39:04.678912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a272d092f2a'
down_revision = 'bee8e7cc7f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ow_match_user', sa.Column('hero_role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ow_match_user', 'ow_hero_role', ['hero_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ow_match_user', type_='foreignkey')
    op.drop_column('ow_match_user', 'hero_role_id')
    # ### end Alembic commands ###
