"""Update to Match table

Revision ID: 823b73b71138
Revises: 10e2c9e15361
Create Date: 2022-03-02 22:56:18.096970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823b73b71138'
down_revision = '10e2c9e15361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ow_hero', sa.Column('hero_role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ow_hero', 'ow_hero_role', ['hero_role_id'], ['id'])
    op.add_column('ow_match', sa.Column('result', sa.Enum('VICTORY', 'DEFEAT', 'DRAW', name='matchresult'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ow_match', 'result')
    op.drop_constraint(None, 'ow_hero', type_='foreignkey')
    op.drop_column('ow_hero', 'hero_role_id')
    # ### end Alembic commands ###
