"""removed name from MatchRound table

Revision ID: b13758d100d5
Revises: 90d43b5584bf
Create Date: 2022-05-03 15:20:32.654539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b13758d100d5'
down_revision = '90d43b5584bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friendship', 'request_accepted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('ow_match_round', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ow_match_round', sa.Column('name', mysql.VARCHAR(length=25), nullable=True))
    op.alter_column('friendship', 'request_accepted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
