"""avatar image table

Revision ID: e271738b13f2
Revises: adbc801d8b1b
Create Date: 2022-05-17 02:02:59.590512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e271738b13f2'
down_revision = 'adbc801d8b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_avatar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user_avatar', ['user_avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_avatar_id')
    # ### end Alembic commands ###
